# Generated by Django 6.0.2 on 2026-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0012_remove_managedopportunity_org_pay_per_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
