# Generated by Django 6.0.2 on 2026-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0114_paymentinvoice_invoice_ticket_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisit",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
