"""The door onto the semantic layer.

`connect_labs.semantic` was proven and unreachable — nothing in the application
imported it, so the workflow named "SQL semantic layer" served numbers frozen into
a saved run rather than numbers that code produced. runtime.evaluate made it
executable; this endpoint is what lets a dashboard ask.
"""

from __future__ import annotations

from unittest.mock import patch

import pytest
from django.urls import reverse

pytestmark = pytest.mark.django_db


def _url(definition_id: int) -> str:
    return reverse("labs:workflow:api_semantic_indicators", args=[definition_id])


def test_the_route_exists_and_is_named():
    assert _url(7).endswith("/api/7/semantic/")


def test_it_passes_the_series_and_scopes_straight_through(client, django_user_model):
    """The two params that decide what comes back. `scopes` matters especially:
    several scopes come from ONE pass via GROUPING SETS, and asking per-scope
    re-runs the entire Layer 1 extraction each time."""
    user = django_user_model.objects.create_user(username="u", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "children", "pipeline_id": 5108}]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": [], "data_source": {"type": "connect_csv"}}

    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.return_value = object()
        ev.return_value = [{"scope": "programme", "n_cases": 2, "n03": 2}]

        resp = client.get(_url(1), {"series": "N", "scopes": "programme,flw"})

    assert resp.status_code == 200
    body = resp.json()
    assert body["series"] == "N"
    assert body["scopes"] == ["programme", "flw"]
    assert body["row_count"] == 1

    kwargs = ev.call_args.kwargs
    assert kwargs["series"] == "N"
    assert kwargs["scopes"] == ["programme", "flw"]


def test_a_workflow_with_no_entity_pipeline_is_refused_with_the_reason(client, django_user_model):
    """Layer 1 is generated from the ENTITY pipeline's own schema, because that is
    where the fallback path lists live — the expensive part, and the thing a
    hand-written extraction has repeatedly dropped."""
    user = django_user_model.objects.create_user(username="u2", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "visits", "pipeline_id": 5109}]
        opportunity_ids = [10042]

    with patch("connect_labs.workflow.views.WorkflowDataAccess") as wda:
        wda.return_value.get_definition.return_value = _Def()
        resp = client.get(_url(1))

    assert resp.status_code == 400
    assert "entity pipeline" in resp.json()["error"]


def test_a_registry_or_sql_failure_is_reported_rather_than_swallowed(client, django_user_model):
    """The message names the missing column or relation, which IS the diagnostic. A
    generic 500 here sends people to the logs for something the response could have
    told them."""
    from connect_labs.semantic.runtime import SemanticRuntimeError

    user = django_user_model.objects.create_user(username="u3", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "children", "pipeline_id": 5108}]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": []}

    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.return_value = object()
        ev.side_effect = SemanticRuntimeError('semantic query failed: column "x" does not exist')

        resp = client.get(_url(1), {"series": "N"})

    assert resp.status_code == 400
    assert 'column "x" does not exist' in resp.json()["error"]


def test_a_missing_workflow_is_a_404_not_a_500(client, django_user_model):
    user = django_user_model.objects.create_user(username="u4", password="p")
    client.force_login(user)
    with patch("connect_labs.workflow.views.WorkflowDataAccess") as wda:
        wda.return_value.get_definition.return_value = None
        resp = client.get(_url(999))
    assert resp.status_code == 404


def test_the_schema_is_converted_to_a_pipeline_config_before_evaluation(client, django_user_model):
    """Layer 1 is generated by the pipeline engine's query builder, which takes an
    AnalysisPipelineConfig - not the schema dict stored on the definition. Using the
    same conversion the dashboard's own pipeline execution uses is what makes the
    compiled extraction identical to the one the dashboard actually runs."""
    user = django_user_model.objects.create_user(username="u5", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "children", "pipeline_id": 5108}]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": [], "terminal_stage": "entity"}

    sentinel = object()
    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.return_value = sentinel
        ev.return_value = []
        resp = client.get(_url(1), {"series": "N"})

    assert resp.status_code == 200
    pda.return_value._schema_to_config.assert_called_once()
    assert ev.call_args.args[0] is sentinel, "the CONFIG must reach evaluate, not the dict"


def test_the_weight_series_pipeline_is_supplied_as_an_extra_field(client, django_user_model):
    """The per-visit WEIGHT is not in the entity pipeline.

    That one carries the registration fields and the visit markers; the weight series
    is a separate pipeline, and properties.yml is written against a `weight_g` column.
    Supplying only the entity pipeline produced, on the live call:

        column "weight_g" does not exist
        HINT: Perhaps you meant to reference the column "visits.weights".

    which is the entity pipeline's LIST-valued weights — a different thing entirely.
    """
    user = django_user_model.objects.create_user(username="u6", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [
            {"alias": "children", "pipeline_id": 5108},
            {"alias": "visits", "pipeline_id": 5109},
        ]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": [{"name": "weight_g"}], "terminal_stage": "visit_level"}

    entity_cfg, visit_cfg = object(), object()
    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.side_effect = [entity_cfg, visit_cfg]
        ev.return_value = []
        resp = client.get(_url(1), {"series": "N"})

    assert resp.status_code == 200
    kwargs = ev.call_args.kwargs
    assert kwargs["extra_fields"] == {
        "weight_g": visit_cfg
    }, "the weight-series config must reach layer 1 as the weight_g column"
    assert ev.call_args.args[0] is entity_cfg


def test_a_cold_cache_is_reported_rather_than_shown_as_zeros(client, django_user_model):
    """Measured live: the first successful call returned HTTP 200 with n_cases 0 and
    every metric zero, because the visit cache had nothing for those opportunities.

    "This programme has no babies" and "nothing has been cached yet" are completely
    different statements, and the numbers cannot tell them apart. This endpoint only
    READS the cache; something else has to populate it.
    """
    user = django_user_model.objects.create_user(username="u7", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "children", "pipeline_id": 5108}]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": [], "terminal_stage": "entity"}

    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.return_value = object()
        ev.return_value = [{"scope": "programme", "n_cases": 0, "n03": 0}]
        resp = client.get(_url(1), {"series": "N"})

    body = resp.json()
    assert body["cold_cache"] is True
    assert "cached" in body["cold_cache_hint"]


def test_real_data_is_not_mislabelled_as_a_cold_cache(client, django_user_model):
    """The inverse, so the notice cannot become noise that people learn to ignore."""
    user = django_user_model.objects.create_user(username="u8", password="p")
    client.force_login(user)

    class _Def:
        pipeline_sources = [{"alias": "children", "pipeline_id": 5108}]
        opportunity_ids = [10042]

    class _Pipe:
        schema = {"fields": [], "terminal_stage": "entity"}

    with (
        patch("connect_labs.workflow.views.WorkflowDataAccess") as wda,
        patch("connect_labs.workflow.data_access.PipelineDataAccess") as pda,
        patch("connect_labs.semantic.runtime.evaluate") as ev,
    ):
        wda.return_value.get_definition.return_value = _Def()
        pda.return_value.get_definition.return_value = _Pipe()
        pda.return_value._schema_to_config.return_value = object()
        ev.return_value = [{"scope": "programme", "n_cases": 8718, "n03": 4168}]
        resp = client.get(_url(1), {"series": "N"})

    body = resp.json()
    assert body["cold_cache"] is False
    assert body["cold_cache_hint"] is None
